{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "def func():\n",
    "    header = {\n",
    "    \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\",\n",
    "    \"Accept-Encoding\": \"gzip, deflate\",\n",
    "    \"Accept-Language\": \"h-CN,zh;q=0.9\",\n",
    "    \"connection\":\"keep-alive\",\n",
    "    \"cookie\":\"ASPSESSIONIDAQSQBCBS=EAAILPFAFPKJAFBDNDPGCNLP; acw_tc=792b121115372620863227399ec6ea3ff6747e0f7534a14d4214f390706122; __51cke__=; ASPSESSIONIDQACBCQRQ=CLKHFMOAAAFCIOPLJGBAGLJH; Hm_lvt_8fd158bb3e69c43ab5dd05882cf0b234=1537262083,1537335891; ASPSESSIONIDSABAARQQ=LGDPFDPAMCLDLHJHGHFJOAAH; ASP.NET_SessionId=y25khumwmzpwmndzq0xq1ku4; ASPSESSIONIDCCACDSTT=NNAFGKPAIONJBEGKBBBMGGEK; acw_sc__v2=NWJhMWY4MTdhMTU0OGY1OWEyM2Q5YTRiMmIwNDZhZGNhYTBmYmI1Mw==; acw_sc__v3=5ba1f87b988eb050b8d12c335d5ed9f965051235; __tins__16949115=%7B%22sid%22%3A%201537340707300%2C%20%22vd%22%3A%2016%2C%20%22expires%22%3A%201537343566641%7D; __51laig__=91; Hm_lpvt_8fd158bb3e69c43ab5dd05882cf0b234=1537341767\",\n",
    "    \"Host\": \"ip.zdaye.com\",\n",
    "    \"Referer\": \"http://ip.zdaye.com/FreeIPlist.html\",\n",
    "    \"Upgrade-Insecure-Requests\": \"1\",\n",
    "    \"User-Agent\": \"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\"\n",
    "        }\n",
    "    url = \"http://ip.zdaye.com/FreeIPlist.html\"\n",
    "    res1 = requests.get(url,headers=header)\n",
    "    res = res1.text.encode(res1.encoding)\n",
    "    res = BeautifulSoup(res,\"lxml\")\n",
    "    return [i.find(\"td\").string for i in res.find(\"tbody\").find_all(\"tr\",class_=False)]\n",
    "\n",
    "def getvalidlist():\n",
    "    tag= True\n",
    "    while tag:\n",
    "        try:\n",
    "            a = func()\n",
    "        except:\n",
    "            tag = True\n",
    "        else:\n",
    "            tag = False\n",
    "    return a\n",
    "\n",
    "def verification(proxy_ip,proxy_port):\n",
    "    header = {\n",
    "    \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\",\n",
    "    \"Accept-Encoding\": \"gzip, deflate\",\n",
    "    \"Accept-Language\": \"h-CN,zh;q=0.9\",\n",
    "    \"connection\":\"keep-alive\",\n",
    "    \"Host\": \"myip.ipip.net\",\n",
    "    \"User-Agent\": \"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\"\n",
    "        }\n",
    "    proxy = {\n",
    "        'http': 'http://%s:%s' % (proxy_ip, proxy_port),\n",
    "        'https': 'https://%s:%s' % (proxy_ip, proxy_port)\n",
    "    }\n",
    "    url = 'http://myip.ipip.net'\n",
    "    try:\n",
    "        text = requests.get(url,headers =header,proxies=proxy,timeout=1.5)\n",
    "        if len(text.text)<100:\n",
    "            print(text.text)\n",
    "            return (proxy_ip,proxy_port)\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(\"Error: \", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error:  HTTPConnectionPool(host='180.150.191.197', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BC8D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.197', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD8588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.197', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD8D68>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.197', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD87B8>, 'Connection to 180.150.191.197 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.197', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BC8F98>, 'Connection to 180.150.191.197 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='211.159.171.58', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7A90>, 'Connection to 211.159.171.58 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='211.159.171.58', port=80): Read timed out. (read timeout=1.5)\n",
      "Error:  HTTPConnectionPool(host='211.159.171.58', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE080>, 'Connection to 211.159.171.58 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='211.159.171.58', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE898>, 'Connection to 211.159.171.58 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='94.242.58.14', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057BE9E8>, 'Connection to 94.242.58.14 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='94.242.58.14', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6E80>, 'Connection to 94.242.58.14 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='94.242.58.14', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6320>, 'Connection to 94.242.58.14 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='94.242.58.14', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8588>, 'Connection to 94.242.58.14 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.78.51.155', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD88D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='120.78.51.155', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BEE390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='120.78.51.155', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BFA1D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='120.78.51.155', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD85C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='120.78.51.155', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='120.78.51.155', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6D68>, 'Connection to 120.78.51.155 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='113.200.56.13', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE7F0>, 'Connection to 113.200.56.13 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='113.200.56.13', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057BEEF0>, 'Connection to 113.200.56.13 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='113.200.56.13', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000057B7780>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='113.200.56.13', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000057BEA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='113.200.56.13', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "当前 IP：47.105.162.22  来自于：中国 山东 青岛  阿里云/电信/联通/移动/铁通/教育网\n",
      "\n",
      "Error:  HTTPConnectionPool(host='47.105.162.22', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE62E8>, 'Connection to 47.105.162.22 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='47.105.162.22', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE8D0>, 'Connection to 47.105.162.22 timed out. (connect timeout=1.5)'))\n",
      "当前 IP：117.191.11.73  来自于：中国 新疆 喀什地区  移动\n",
      "\n",
      "当前 IP：117.191.11.73  来自于：中国 新疆 喀什地区  移动\n",
      "\n",
      "当前 IP：47.105.160.32  来自于：中国 山东 青岛  阿里云/电信/联通/移动/铁通/教育网\n",
      "\n",
      "Error:  HTTPConnectionPool(host='47.105.160.32', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE198>, 'Connection to 47.105.160.32 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='47.105.160.32', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8240>, 'Connection to 47.105.160.32 timed out. (connect timeout=1.5)'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error:  HTTPConnectionPool(host='106.75.135.245', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BFA358>, 'Connection to 106.75.135.245 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.135.245', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE8D0>, 'Connection to 106.75.135.245 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.135.245', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE62E8>, 'Connection to 106.75.135.245 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.135.245', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6978>, 'Connection to 106.75.135.245 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='123.207.91.165', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BC8DD8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='123.207.91.165', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD80B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='123.207.91.165', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000057B7358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='123.207.91.165', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000057BEEF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='123.207.91.165', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD8E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='123.207.91.165', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6CF8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPSConnectionPool(host='online.ataoge.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))\n",
      "Error:  HTTPSConnectionPool(host='online.ataoge.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))\n",
      "Error:  HTTPSConnectionPool(host='online.ataoge.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))\n",
      "当前 IP：183.6.117.104  来自于：中国 广东 广州  电信\n",
      "\n",
      "Error:  HTTPConnectionPool(host='27.154.240.222', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE60B8>, 'Connection to 27.154.240.222 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='27.154.240.222', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE4A8>, 'Connection to 27.154.240.222 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='27.154.240.222', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEEF98>, 'Connection to 27.154.240.222 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='27.154.240.222', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BFA9E8>, 'Connection to 27.154.240.222 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.217', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE7B8>, 'Connection to 120.132.52.217 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.217', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE62B0>, 'Connection to 120.132.52.217 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.217', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6908>, 'Connection to 120.132.52.217 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.217', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8EB8>, 'Connection to 120.132.52.217 timed out. (connect timeout=1.5)'))\n",
      "当前 IP：140.143.105.245  来自于：中国 重庆 重庆  电信/联通/移动\n",
      "\n",
      "当前 IP：140.143.105.245  来自于：中国 重庆 重庆  电信/联通/移动\n",
      "\n",
      "Error:  HTTPConnectionPool(host='120.132.52.220', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD85F8>, 'Connection to 120.132.52.220 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.220', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7630>, 'Connection to 120.132.52.220 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.220', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7B70>, 'Connection to 120.132.52.220 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.220', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE67F0>, 'Connection to 120.132.52.220 timed out. (connect timeout=1.5)'))\n",
      "当前 IP：39.137.69.9  来自于：中国 天津 天津  移动\n",
      "\n",
      "当前 IP：39.137.69.9  来自于：中国 天津 天津  移动\n",
      "\n",
      "Error:  HTTPConnectionPool(host='218.60.8.99', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6BE0>, 'Connection to 218.60.8.99 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='218.60.8.99', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE7B8>, 'Connection to 218.60.8.99 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='218.60.8.99', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEEEB8>, 'Connection to 218.60.8.99 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='218.60.8.99', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8978>, 'Connection to 218.60.8.99 timed out. (connect timeout=1.5)'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error:  HTTPConnectionPool(host='118.190.95.43', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD8588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='118.190.95.43', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BEE748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='118.190.95.43', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE4A8>, 'Connection to 118.190.95.43 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='118.190.95.43', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='118.190.95.43', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6B70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='118.190.95.43', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BC8F60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.127', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7358>, 'Connection to 106.75.140.127 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.127', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7B00>, 'Connection to 106.75.140.127 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.127', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6E48>, 'Connection to 106.75.140.127 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.127', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6AC8>, 'Connection to 106.75.140.127 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='171.221.239.11', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEEAC8>, 'Connection to 171.221.239.11 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='171.221.239.11', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE438>, 'Connection to 171.221.239.11 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='171.221.239.11', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8AC8>, 'Connection to 171.221.239.11 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='171.221.239.11', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BFA7B8>, 'Connection to 171.221.239.11 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.53.31', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD84A8>, 'Connection to 120.132.53.31 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.53.31', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE160>, 'Connection to 120.132.53.31 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.53.31', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE7B8>, 'Connection to 120.132.53.31 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.53.31', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6EF0>, 'Connection to 120.132.53.31 timed out. (connect timeout=1.5)'))\n",
      "当前 IP：117.191.11.71  来自于：中国 新疆 喀什地区  移动\n",
      "\n",
      "当前 IP：117.191.11.71  来自于：中国 新疆 喀什地区  移动\n",
      "\n",
      "Error:  HTTPConnectionPool(host='106.75.135.248', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6668>, 'Connection to 106.75.135.248 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.135.248', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B72E8>, 'Connection to 106.75.135.248 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.135.248', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BFA9E8>, 'Connection to 106.75.135.248 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.135.248', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7A90>, 'Connection to 106.75.135.248 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.134', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6358>, 'Connection to 120.132.52.134 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.134', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6AC8>, 'Connection to 120.132.52.134 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.134', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE470>, 'Connection to 120.132.52.134 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.134', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE828>, 'Connection to 120.132.52.134 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='110.167.30.50', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8C88>, 'Connection to 110.167.30.50 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='110.167.30.50', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8358>, 'Connection to 110.167.30.50 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='110.167.30.50', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEEF28>, 'Connection to 110.167.30.50 timed out. (connect timeout=1.5)'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error:  HTTPConnectionPool(host='110.167.30.50', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE668>, 'Connection to 110.167.30.50 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.220', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.220', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE69B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.220', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000057B7630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.220', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BFABE0>, 'Connection to 180.150.191.220 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='180.150.191.220', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7B70>, 'Connection to 180.150.191.220 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='179.189.248.182', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6D68>, 'Connection to 179.189.248.182 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='179.189.248.182', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6F28>, 'Connection to 179.189.248.182 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='179.189.248.182', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE7B8>, 'Connection to 179.189.248.182 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='179.189.248.182', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE898>, 'Connection to 179.189.248.182 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.60', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8128>, 'Connection to 106.75.140.60 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.60', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BFA4E0>, 'Connection to 106.75.140.60 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.60', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8978>, 'Connection to 106.75.140.60 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='106.75.140.60', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE3C8>, 'Connection to 106.75.140.60 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='183.129.207.73', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BEE748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='183.129.207.73', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='183.129.207.73', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE69B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='202.117.115.6', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7668>, 'Connection to 202.117.115.6 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='202.117.115.6', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057BEB38>, 'Connection to 202.117.115.6 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='121.140.126.250', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6860>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='121.140.126.250', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BEECC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='121.140.126.250', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BEE358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='121.140.126.250', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD81D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='121.140.126.250', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BFA2B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='121.140.126.250', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD8C18>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BEE748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE64A8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='117.114.149.66', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='36.89.148.117', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE64E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='36.89.148.117', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000057BE9B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='36.89.148.117', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD87B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.194', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BC8EF0>, 'Connection to 120.132.52.194 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.194', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEEF28>, 'Connection to 120.132.52.194 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.194', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000057B7828>, 'Connection to 120.132.52.194 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.194', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE390>, 'Connection to 120.132.52.194 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.142', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BEE710>, 'Connection to 120.132.52.142 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.142', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8748>, 'Connection to 120.132.52.142 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.142', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BD8470>, 'Connection to 120.132.52.142 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='120.132.52.142', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE69E8>, 'Connection to 120.132.52.142 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='39.108.128.242', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BE6940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='39.108.128.242', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BFABE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n",
      "Error:  HTTPConnectionPool(host='39.108.128.242', port=80): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000000007BE6390>, 'Connection to 39.108.128.242 timed out. (connect timeout=1.5)'))\n",
      "Error:  HTTPConnectionPool(host='39.108.128.242', port=8080): Max retries exceeded with url: http://myip.ipip.net/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007BD84E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mConnectionRefusedError\u001b[0m                    Traceback (most recent call last)",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\u001b[0m in \u001b[0;36mcreate_connection\u001b[1;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[0;32m     72\u001b[0m                 \u001b[0msock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbind\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msource_address\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 73\u001b[1;33m             \u001b[0msock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msa\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     74\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0msock\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mConnectionRefusedError\u001b[0m: [WinError 10061] 由于目标计算机积极拒绝，无法连接。",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-2-d2433e303848>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      9\u001b[0m             \u001b[0mtime2\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtime1\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     10\u001b[0m             \u001b[1;32mwhile\u001b[0m \u001b[0mtime2\u001b[0m\u001b[1;33m-\u001b[0m\u001b[0mtime1\u001b[0m\u001b[1;33m<\u001b[0m\u001b[1;36m3\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 11\u001b[1;33m                 \u001b[0mm\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mverification\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mproxy_ip\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mproxy_port\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     12\u001b[0m                 \u001b[1;32mif\u001b[0m \u001b[0mtype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mm\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m==\u001b[0m\u001b[0mtuple\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     13\u001b[0m                     \u001b[1;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"e:/wenpeiyu/proxy.txt\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;34m\"a\"\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m<ipython-input-1-5f2c6b26fb9d>\u001b[0m in \u001b[0;36mverification\u001b[1;34m(proxy_ip, proxy_port)\u001b[0m\n\u001b[0;32m     45\u001b[0m     \u001b[0murl\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m'http://myip.ipip.net'\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     46\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 47\u001b[1;33m         \u001b[0mtext\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mheaders\u001b[0m \u001b[1;33m=\u001b[0m\u001b[0mheader\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mproxies\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mproxy\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m1.5\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     48\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtext\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m<\u001b[0m\u001b[1;36m100\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     49\u001b[0m             \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtext\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(url, params, **kwargs)\u001b[0m\n\u001b[0;32m     70\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     71\u001b[0m     \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msetdefault\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'allow_redirects'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 72\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'get'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     73\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     74\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(method, url, **kwargs)\u001b[0m\n\u001b[0;32m     56\u001b[0m     \u001b[1;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     57\u001b[0m     \u001b[1;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 58\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     59\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     60\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    506\u001b[0m         }\n\u001b[0;32m    507\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 508\u001b[1;33m         \u001b[0mresp\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    509\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    510\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    616\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    617\u001b[0m         \u001b[1;31m# Send the request\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 618\u001b[1;33m         \u001b[0mr\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    619\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    620\u001b[0m         \u001b[1;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    438\u001b[0m                     \u001b[0mdecode_content\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    439\u001b[0m                     \u001b[0mretries\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmax_retries\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 440\u001b[1;33m                     \u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    441\u001b[0m                 )\n\u001b[0;32m    442\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    599\u001b[0m                                                   \u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtimeout_obj\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    600\u001b[0m                                                   \u001b[0mbody\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mbody\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 601\u001b[1;33m                                                   chunked=chunked)\n\u001b[0m\u001b[0;32m    602\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    603\u001b[0m             \u001b[1;31m# If we're going to release the connection in ``finally:``, then\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    355\u001b[0m             \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrequest_chunked\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mhttplib_request_kw\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    356\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 357\u001b[1;33m             \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mhttplib_request_kw\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    358\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    359\u001b[0m         \u001b[1;31m# Reset the timeout for the recv() on the socket\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(self, method, url, body, headers, encode_chunked)\u001b[0m\n\u001b[0;32m   1237\u001b[0m                 encode_chunked=False):\n\u001b[0;32m   1238\u001b[0m         \u001b[1;34m\"\"\"Send a complete request to the server.\"\"\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1239\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_send_request\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbody\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mencode_chunked\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1240\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1241\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_send_request\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbody\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mencode_chunked\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36m_send_request\u001b[1;34m(self, method, url, body, headers, encode_chunked)\u001b[0m\n\u001b[0;32m   1283\u001b[0m             \u001b[1;31m# default charset of iso-8859-1.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1284\u001b[0m             \u001b[0mbody\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_encode\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbody\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'body'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1285\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mendheaders\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbody\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mencode_chunked\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mencode_chunked\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1286\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1287\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mgetresponse\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36mendheaders\u001b[1;34m(self, message_body, encode_chunked)\u001b[0m\n\u001b[0;32m   1232\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1233\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mCannotSendHeader\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1234\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_send_output\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage_body\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mencode_chunked\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mencode_chunked\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1235\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1236\u001b[0m     def request(self, method, url, body=None, headers={}, *,\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36m_send_output\u001b[1;34m(self, message_body, encode_chunked)\u001b[0m\n\u001b[0;32m   1024\u001b[0m         \u001b[0mmsg\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34mb\"\\r\\n\"\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_buffer\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1025\u001b[0m         \u001b[1;32mdel\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_buffer\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1026\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1027\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1028\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mmessage_body\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\http\\client.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, data)\u001b[0m\n\u001b[0;32m    962\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msock\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    963\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mauto_open\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 964\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    965\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    966\u001b[0m                 \u001b[1;32mraise\u001b[0m \u001b[0mNotConnected\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\u001b[0m in \u001b[0;36mconnect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    164\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    165\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mconnect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 166\u001b[1;33m         \u001b[0mconn\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_new_conn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    167\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_prepare_conn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    168\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\u001b[0m in \u001b[0;36m_new_conn\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    139\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    140\u001b[0m             conn = connection.create_connection(\n\u001b[1;32m--> 141\u001b[1;33m                 (self.host, self.port), self.timeout, **extra_kw)\n\u001b[0m\u001b[0;32m    142\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    143\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[0mSocketTimeout\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\u001b[0m in \u001b[0;36mcreate_connection\u001b[1;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[0;32m     71\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0msource_address\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     72\u001b[0m                 \u001b[0msock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbind\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msource_address\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 73\u001b[1;33m             \u001b[0msock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msa\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     74\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0msock\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     75\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import time \n",
    "tupleport = (\"80\",\"8080\")#,\"8060\",\"1080\",\"3128\",\"9898\")\n",
    "lst = []\n",
    "while True:\n",
    "    a = getvalidlist()\n",
    "    for proxy_ip in a:\n",
    "        for proxy_port in tupleport:\n",
    "            time1 = time.time()\n",
    "            time2 = time1\n",
    "            while time2-time1<3:\n",
    "                m = verification(proxy_ip,proxy_port)\n",
    "                if type(m)==tuple:\n",
    "                    with open(\"e:/wenpeiyu/proxy.txt\",\"a\") as f:\n",
    "                        f.write(\"{}\\n\".format(m))\n",
    "                        break \n",
    "\n",
    "                time2 = time.time()\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
